.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH amazeing 1  "amazeing " 
.SH NAME
amazeing
.SH SYNOPSIS
\fBamazeing view\fR <\fB\-m\fR|\fB\-\-maze\fR> [\fB\-u\fR|\fB\-\-update\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-m\fR, \fB\-\-maze\fR=\fIMAZE\fR
Maze file path
.TP
\fB\-u\fR, \fB\-\-update\fR
View and update
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
