.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH amazeing 1  "amazeing 0.3.4" 
.SH NAME
amazeing \- A maze generator/solver application with simulation/visualization
.SH SYNOPSIS
\fBamazeing\fR [\fB\-Z\fR|\fB\-\-zoom\fR] [\fB\-C\fR|\fB\-\-colors\fR] [\fB\-F\fR|\fB\-\-fps\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
A maze generator/solver application with simulation/visualization.
.PP
See https://eendroroy.github.io/amazeing for more details
.SH OPTIONS
.TP
\fB\-Z\fR, \fB\-\-zoom\fR=\fIZOOM\fR [default: 1]
Display size (zoom)
.TP
\fB\-C\fR, \fB\-\-colors\fR=\fIColors.toml\fR
Color file (.toml) path
.TP
\fB\-F\fR, \fB\-\-fps\fR=\fIFPS\fR [default: 60]
Frame rate per second (controls simulation speed)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
amazeing\-create(1)
Create a Maze
.TP
amazeing\-view(1)
View a Maze
.TP
amazeing\-solve(1)
Solve a Maze
.TP
amazeing\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.3.4
