.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH amazeing 1  "amazeing " 
.SH NAME
amazeing
.SH SYNOPSIS
\fBamazeing solve\fR <\fB\-m\fR|\fB\-\-maze\fR> [\fB\-p\fR|\fB\-\-procedure\fR] [\fB\-H\fR|\fB\-\-heuristic\-function\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-m\fR, \fB\-\-maze\fR=\fIMAZE\fR
Maze file path
.TP
\fB\-p\fR, \fB\-\-procedure\fR=\fIPROCEDURE\fR [default: dfs]
Maze Solving Procedure
.br

.br
[\fIpossible values: \fRbfs, dfs, dijkstra, a\-star]
.TP
\fB\-H\fR, \fB\-\-heuristic\-function\fR=\fIHEURISTIC_FUNCTION\fR [default: dijkstra]
Heuristic function (to use with AStar)
.br

.br
[\fIpossible values: \fRmanhattan, euclidean, chebyshev, octile, dijkstra]
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show a simulation of the generation process
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
