color_bg = 0x000000
color_block = 0x032606
color_open = 0xcbe7d2
color_visiting = 0x4d6d27
color_visiting_peak = 0xeeff00
color_path = 0x70f93e
color_source = 0x66ff00
color_destination = 0x00ff40
color_traversed = 0x889385