color_bg = 0x000000
color_block = 0x062209
color_open = 0x7f9169
color_visiting = 0x403b3e
color_visiting_peak = 0xffff00
color_path = 0x359014
color_source = 0x66ff00
color_destination = 0x00ff40
color_traversed = 0x403b3e
color_perimeter = 0x403b3e