color_bg = 0x0f0000
color_block = 0x240101
color_open = 0xbd9d9d
color_visiting = 0xa43232
color_visiting_peak = 0x7ffc03
color_path = 0xe81515
color_source = 0xaa0505
color_destination = 0x7ffc03
color_traversed = 0x9b6969
color_perimeter = 0x9b6969