color_bg = 0x0f0000
color_block = 0x240101
color_open = 0xbd9d9d
color_visiting = 0xa43232
color_visiting_peak = 0xffbc05
color_path = 0xe81515
color_source = 0xf70505
color_destination = 0xff70505
color_traversed = 0x9b6969